### ISSUE TITLE
Does not like when there is a space in the pixel overlay model name

### ISSUE THREAD

**Issue by nmiller0113** [LightsOnHudson/FPP-Plugin-Matrix-Message#1]
After working with Ben to get this setup I decided to test it out.  I ran my test and there were no errors being logged...everything seemed to execute as it should...though nothing showed up on my Matrix.  The Matrix Tools testing would work just fine, so it confirmed I had it configured properly.  So I then decided to run the same command the script was running, manually from the CLI, and immediately saw an error that was not showing up in the logs:

fpp@fpp ~/media/plugins/fpp-matrixtools/scripts $ ./matrixtools --blockname "Livingroom+Matrix" --color 'yellow' --font DejaVuSans-Bold --fontsize 18 --pixelspersecond 20 --message " Testing  "
ERROR: Unable to find block named 'Livingroom+Matrix'

I assumed this was because it wasn't properly handling the space in the name of the pixel overlay model Livingroom Matrix.  So I changed the name to livingroommatrix and tested again.  Success!  I don't know if there is a way to fix this easily but I imagine there probably is.  You may also want to consider logging any responses from the matrixtools script too so we'd see issues like this in the logs.

Working great otherwise!  Thanks again!

**Comment by LightsOnHudson** [comment]
I see the error, yes, this is an EASY fix. I'll make the fix and have you
test it out for me. Correct. i store the name encoded and that encodes all
characters including spaces. I dont un-encode / decrypt it on this area.
I"ll make the fix this morning.

**Comment by LightsOnHudson** [comment]
THis has been fixed. please update.
